[selene]
base = "lua51"
name = "vim"

[vim]
any = true

[jit]
any = true

[assert]
any = true

[describe]
any = true

[it]
any = true

[before_each]
any = true

[after_each]
any = true

[setup]
any = true

[teardown]
any = true
